import { Providers } from "./providers";
import { Inter } from "next/font/google";
import "./globals.css";
import WithSubnavigation from "@/components/Navbar";
import SmallWithSocial from "@/components/footer";
import AuthProvider from "@/components/AuthProvider";
import { auth } from "@/auth";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const session = await auth();

  console.log(session);
  return (
    <AuthProvider>
      <html lang="en">
        <body className={inter.className}>
          <Providers>
            <WithSubnavigation isLoggedIn={!session ? false : true} />
            {children}
            {/* <SmallWithSocial /> */}
          </Providers>
        </body>
      </html>
    </AuthProvider>
  );
}
